import { IpResponseType } from '../types/ipTypes';

export const mockIpData: IpResponseType = {
  ip: '45.138.153.39',
  network: '45.138.152.0/23',
  version: 'IPv4',
  city: 'Gmina Piątek',
  region: 'Łódź Voivodeship',
  region_code: '10',
  country: 'PL',
  country_name: 'Poland',
  country_code: 'PL',
  country_code_iso3: 'POL',
  country_capital: 'Warsaw',
  country_tld: '.pl',
  continent_code: 'EU',
  in_eu: true,
  postal: '99-120',
  latitude: 52.0696,
  longitude: 19.4734,
  timezone: 'Europe/Warsaw',
  utc_offset: '+0100',
  country_calling_code: '+48',
  currency: 'PLN',
  currency_name: 'Zloty',
  languages: 'pl',
  country_area: 312685,
  country_population: 37978548,
  asn: 'AS50411',
  org: 'ITV Media Sp. z o.o.',
};
